import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const teamsData = [
  {
    name: "Coordenação Geral",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Ariele Menezes de Arruda Gesteira",
        wifePhone: "(61) 98266-7769",
        husbandName: "Tio Marcus Vínicius Nunes Gesteira",
        husbandPhone: "(61) 99860-4341",
        address: "QR 1A Conj T casa 20 - Candangolândia",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Anaila Mizuta da Silva",
        address: "SGAN 912 Bloco F Apto 215 - Asa Norte",
        phone: "(61) 99114-6771",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Henrique Lima Ferreira",
        address: "702/703 Bloco B Ent 52 Ed. Benvenuto Ap 114 - Asa Norte",
        phone: "(34) 99111-6410",
      },
    ],
  },
  {
    name: "Compras",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Adriana Moura Maia",
        wifePhone: "(61) 98448-8368",
        husbandName: "Tio Roberto César de Oliveir Viégas",
        husbandPhone: "(11) 98805-1000",
        address: "SQNW 311 Bloco F Apto 102 - Noroeste",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Iasmin Lyara Cabral da Silva",
        address: "QS 4, Conjunto 7, Casa 27 - DF",
        phone: "(61) 99619-7913",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "José de Oliveira Cruz",
        address: "Colina, Bloco K, Apt 201, Casa do Estudante - Asa Norte",
        phone: "(61) 98112-9199",
      },
    ],
  },
  {
    name: "Sala",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Nathalia Damaceno Hott Dias",
        wifePhone: "(61) 98153-3699",
        husbandName: "Tio Eduardo Dias Leite Junior",
        husbandPhone: "(61) 98401-7304",
        address: "SHCGN 703, Bloco F, Casa 13 - DF",
      },
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Rafaela Cardoso Fernandes",
        wifePhone: "(21) 99832-0591",
        husbandName: "Tio Cristian de Macena Chagas Fernandes",
        husbandPhone: "(21) 99842-3185",
        address: "SHCES 605, bloco C, apto 405 - Cruzeiro Novo",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Laura Lopes Pavão da Silva",
        address: "SQN 103 Bloco G Apartamento 303",
        phone: "(61) 99385-9779",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Luiz Felipe Castilho Torres",
        address: "SQN 103 Bloco C Apto 403 - Asa Norte",
        phone: "(61) 99315-9738",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Warley Faria Bueno",
        address: "Avenida Central, lote 233 Apto 202 - Nucleo Bandeirante",
        phone: "(61) 99517-1493",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Hévila Maria Chaves Monte",
        address: "SQN 213 Bloco B - Asa Norte",
        phone: "(86) 99904-4249",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Rafael Lannes Florenzano de Souza",
        address: "SQN 102 Bloco F Apto 603 - Asa Norte",
        phone: "(61) 98112-6190",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Irlana Nunes de Souza",
        address: "Quadra 3, Conj. 2, Casa 21 - Taquari",
        phone: "(61) 99558-3923",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Laura Cristina Silva",
        address: "QD 4 Conj. E Casa 17 - Candangolândia",
        phone: "(61) 99853-0244",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Wesley Mailson dos Santos",
        address: "Avenida do Exército - Setor Militar",
        phone: "(61) 98339-6867",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Raphael Villela de Paiva",
        address: "SQN 406 Bloco M Apto 205 - Asa Norte",
        phone: "(61) 98197-6389",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Bruno Afonso Salum",
        address: "SQN 211 Bloco F Apto 606 - Asa Norte",
        phone: "(61) 99987-8122",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Lucas Alves Flores",
        address: "Av. do exercito SMU",
        phone: "(31) 99336-4393",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Nórton Santarém dos Santos",
        address: "Rua das Gamelas chácara 27 Núcleo Rural Nova Betânia - São Sebastião",
        phone: "(37) 99952-3681",
      },
    ],
  },
  {
    name: "Garçons",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Roberta Cristina Silva Rocha",
        wifePhone: "(61) 99848-4815",
        husbandName: "Tio Ederson Rocha Lima Silva",
        husbandPhone: "(61) 99643-2140",
        address: "Quadra 1 chac 7H bloco J apto 01 - Valparaíso",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Andressa de Souza Cardozo",
        address: "SQN 306 Apto 202 - Asa Norte",
        phone: "(61) 98193-9841",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Bruna Teixeira Dias",
        address: "QE 40, Rua 10, Lote 21, Apto 102 - Guará",
        phone: "(61) 99382-5091",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Maria Clara Silva Oliveira",
        address: "SQN 115 Bloco E Apto 307 - Asa Norte",
        phone: "(61) 98266-7352",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Iury Xavier Bomfim",
        address: "SHCES 913, Bloco B, Apartamento 405 - DF",
        phone: "(61) 99850-8877",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriel Hinkel Ubiali",
        address: "SQS 404 Bloco G Apt 106 - Asa Sul",
        phone: "(61) 98102-8453",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "João Lucas Indalécio Nascimento Herculano",
        address: "QRO, Conjunto H, Casa 14, Candangolândia-DF",
        phone: "(61) 98227-2913",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Lucas Gabriel Almeida Barbosa Santos",
        address: "SHCES, Quadra 609, Bloco B, Apartamento 405, Cruzeiro-DF",
        phone: "(61) 99693-0054",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Stephanie de Lima Dantas",
        address: "Quadra 116 cj 6 casa 20 recanto das emas",
        phone: "(61) 98509-7588",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Fabiene Lopes de Vasconcelos",
        address: "Qd 7c Conj B casa 1A (arapoangas)",
        phone: "(61) 99515-8389",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Emanuella Santana de Souza",
        address: "Quadra 14 conjunto L casa 08/ Araponga-DF",
        phone: "(61) 9818-4177 ?",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Dinael cordeiro cunha",
        address: "rua f lote 27, vila real, arapoangas planaltina",
        phone: "(61) 98192-5211",
      },
    ],
  },
  {
    name: "Mini Mercado",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Paloma Nunes Gesteira Permigiani",
        wifePhone: "(61) 99629-0953",
        husbandName: "Tio Matheus de Oliveira Permigiani",
        husbandPhone: "(61) 98240-8176",
        address: "QS 16, Conjunto 7, Casa 20, Riacho Fundo",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Maria Clara Lopes de Barros",
        address: "SQPS 102, Lote 19 Bloco D Apto 102 - Guará",
        phone: "(61) 99129-1860",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Júlia Maria Oliveira Gomes",
        address: "QE 20 Conj. P Lote 14 - Guará",
        phone: "(61) 98294-3322",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Jessica Barbosa das Chagas",
        address: "711 BL G Ent 41, Apt 103 - ASA NORTE",
        phone: "(31) 98702-5465",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriella Julia Soares dos Santos",
        address: "Condomínio RK conjunto Antares quadra D casa 4 - Sobradinho",
        phone: "(61) 98615-3752",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Ana Júlia Fagundes Pereira",
        address: "SQSW 500 Bloco Q Apto 306 - Sudoeste",
        phone: "(61) 99380-0942",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Lorena da Rocha Sousa",
        address: "Quadra 511 conjunto 16 casa 16 - Recanto das Emas",
        phone: "(61) 99525-1669",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "France Kelly de Morais Lopes",
        address: "Quadra 510 Conjunto 13 Casa 11 - Recanto das Emas",
        phone: "(61) 98449-9549",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Loyse Wianê da Silva",
        address: "Quadra 111 conjunto 10 casa 18 - Recanto das Emas",
        phone: "(61) 99197-1896",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Luan Sousa",
        address: "Quadra 4M Conjunto B Casa 08 - Arapoanga/DF",
        phone: "(61) 99464-9429",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Laís Santos Fiuza",
        address: "Quadra 15/17 M conjunto C casa 67 Arapoangas - Planaltina DF",
        phone: "(61) 99225-8451",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Bruna Soares de Castro",
        address: "Quadra 9E conjunto A casa 28 Araponga",
        phone: "(61) 99558-1829",
      },
    ],
  },
  {
    name: "Cafezinho",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Carla Daniele dos Santos Nascimento",
        wifePhone: "(61) 98280-7865",
        husbandName: "Tio Felipe Weider do Nascimento",
        husbandPhone: "(61) 98209-7859",
        address: "Quadra 106 Conjunto 1 Casa 08 Cond. Alto da Boa Vista",
      },
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Maria Janiele de Lima Carneiro",
        wifePhone: "(61) 99907-1776",
        husbandName: "Tio Matheus Andrade de Lima",
        husbandPhone: "(61) 99936-3008",
        address: "Quadra 22, Md 1 lote 3, bloco 12 apto 302 - Planaltina",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Gabriel Lannes Florenzano de Souza",
        address: "SQN 102 Bloco F Apto 603 - Asa Norte",
        phone: "(61) 98379-6809",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Pietra Cantanhede Souza de Moraes Nunes Damascena",
        address: "QE 17 Conj. B Casa 27 - Guará",
        phone: "(61) 99838-0811",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Marina Martins Gagliard",
        address: "SQN 208 Bloco J Apto 601 - Asa Norte",
        phone: "(61) 98370-2121",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Eduardo Alves Santana",
        address: "SHN Quadra 01, Área Especial A, Blobo B, Asa Norte",
        phone: "(88) 99237-5146",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Ana Luiza Gonçalves Veloso",
        address: "Quadra F lote 01 Vila Paraiso 02 - Santo Antônio do Descoberto",
        phone: "(61) 98502-0250",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Ana Clara Roque da Silva",
        address: "Qd 116 conj 04 casa 12",
        phone: "(61) 99351-0083",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriella Cesa de Jesus",
        address: "Recanto das Emas Qua 300 Conj 39 Casa 04",
        phone: "(61) 99963-0858",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Glenda Pereira de Oliveira",
        address: "Quadra 802 Conj 04 casa 23 - Recanto das Emas",
        phone: "(61) 99602-6073",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Luiz Henrique Santos Souza",
        address: "Quadra 12 conjunto N casa 37 arapoangas",
        phone: "(61) 98200-8417",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Raylon Alves dos Santos",
        address: "Quadra 5 conjunto N casa 48a Planaltina DF",
        phone: "(61) 99278-1916",
      },
    ],
  },
  {
    name: "Cozinha",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Valéria Alves Pereira",
        wifePhone: "(12) 99772-1814",
        husbandName: "Tio Athayr Araújo Pereira Junior",
        husbandPhone: "(12) 99762-2337",
        address: "SQN 113 BL D Apto 509",
      },
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Ivanice Torres de Medeiros",
        wifePhone: "(85) 99970-7321",
        husbandName: "Tio Antônio Júnior Leite Minervino",
        husbandPhone: "(85) 99855-7983",
        address: "SQN 113, bloco J, apto 102",
      },
      {
        type: "JOVEM",
        subcategory: "Casal apoio",
        name: "Tio Marcelo Garrido Pereira",
        address: "SHCGN 716 Bloco I Casa 29, Asa Norte",
        phone: "(61) 99970-0149",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Juliana Alves de Seixa",
        address: "SQNW 302 Bloco C Apto 609 - Noroeste",
        phone: "(61) 98143-2500",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriell de Luccas Rêgo Lourenço",
        address: "Cond. RK Conj. Antares Quadra 12 - Sobradinho",
        phone: "(61) 99831-8309",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Fabiana Merola Simões Marinho",
        address: "SHIN QI 08 Conjunto 07 Casa 12 - Lago Norte",
        phone: "(61) 99177-5346",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Priscila Lima Costa",
        address: "SQN 411 Bloco J Apt 01 - Asa Norte",
        phone: "(61) 98233-7832",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Nicoly Ribeiro dos Santos",
        address: "quadra 510 conjunto 18 casa 10 Recanto das Emas",
        phone: "(61) 99266-9981",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Laryssa Queiroz de Lima",
        address: "quadra 510 conjunto: 18 Casa: 32 Recanto das Emas",
        phone: "(61) 99308-3590",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Thauany Silva da Conceição",
        address: "quadra 509 conjunto 15 casa 17 Recanto das emas",
        phone: "(61) 99319-9282",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Pablo Henrique Santos da Rocha",
        address: "Q 510 cj 18 lt 32 Recanto das Emas",
        phone: "(61) 99615-5844",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Mariana Lima de Andrade",
        address: "quadra 16 conjunto F casa 10 Araponga",
        phone: "(61) 99162-0021",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Charlie César Dias de Castro",
        address: "quadra 7 conjunto 4 casa 2 Arapoanga",
        phone: "(61) 99301-3356",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Levi de Araújo dos Santos",
        address: "quadra 21 conjunto F casa 19 B , arapoangas ,planaltina DF",
        phone: "(61) 99556-0752",
      },
    ],
  },
  {
    name: "Liturgia",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Gessi dos Reis Oliveira",
        wifePhone: "(61) 99224-5287",
        husbandName: "Tio Adão Oliveira",
        husbandPhone: "(61) 99404-4285",
        address: "QN 7 Conjunto 16 Casa 09 - Riacho Fundo I",
      },
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Kelly Abadia Simas Farias",
        wifePhone: "(61) 98186-7966",
        husbandName: "Tio Carlos Henrique Sales Simas Farias",
        husbandPhone: "(61) 981286222",
        address: "SQN 303 Bloco D Apto 212",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Mariana Rodrigues de Brito",
        address: "Qr 03 Conjunto F Casa 23 – Candangolândia",
        phone: "(61) 99949-4918",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Erica Braga Pereira",
        address: "SQN 212 Bloco C, Apto 413 - Asa Norte",
        phone: "(61) 98197-7390",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Thaise Almeida Nunes Vasconcelos",
        address: "QMSW 6 lot 4 apto 236 - Sudoeste",
        phone: "(71) 99901-8215",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Mariana Leão de Oliveira",
        address: "4 Conj G, casa 10 - Guará II",
        phone: "(61) 99103-6029",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Matheus Leão de Oliveira",
        address: "QE 4 Conj. G, Casa 10 - Guará II",
        phone: "(61) 98457-9027",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Arthur Juan Ramos dos Santos",
        address: "QE 40 rua 8 lote 20 apto 203 - Guará II",
        phone: "(61) 99529-1311",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Alice Sousa da Silva",
        address: "Rua 1, Lote 12, 08 - Vila Telebrasília",
        phone: "(61) 99312-4111",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Jhonatas Araújo da Silva",
        address: "Quadra 301 Bloco Q apto 301 - Total Ville",
        phone: "(61) 99117-4708",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Maria Helena Monteiro de Souza",
        address: "Quadra 55 Conjunto F casa 276 Brazlândia - DF",
        phone: "(61) 99863-1209",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Isayas da Silva Matos",
        address: "Qd 10, Cj F, Cs 20 Arapoanga",
        phone: "(61) 99204-0866",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Beatriz de Oliveira Santana",
        address: "Quadra 13 conjunto I casa 16 A",
        phone: "(61) 99427-9776",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Sabrina Fernandes Tavares",
        address: "Quadra 1 conjunto i casa 49 Arapoanga-DF",
        phone: "(61) 99205-3003",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Marcos Antônio Lima de Andrade",
        address: "Quadra 16 conjunto F casa 10 - Arapoanga",
        phone: "(61) 99233-0485",
      },
    ],
  },
  {
    name: "Vigília Externa",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Isabela Coelho",
        wifePhone: "(61) 98681-2318",
        husbandName: "Tio Vitor Mariano",
        husbandPhone: "(61) 98491-8881",
        address: "QS 14 conj. 3B lote 02 Ap 101 - Riacho Fundo I",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Aline Ferreira Cavalcante Souza",
        address: "SCLRN 705, Bloco G, Entrequadras 46, Asa Norte",
        phone: "(77) 99847-6915",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Flávia Taumaturgo Bento",
        address: "SHIN QL 6 Conj. 5 Casa 17 - Lago Norte",
        phone: "(61) 98164-4093",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Maria Luiza Farias de Oliveira",
        address: "QE 24 Conj. G casa 27 - Guará II",
        phone: "(61) 98321-6579",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Natássia Veruska Pereira Pinheiro",
        address: "SQN 410 Bloco M 105 - Asa Norte",
        phone: "(61) 98501-1904",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Alef Eduardo",
        address: null,
        phone: "(61) 99615-1461",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gustavo Sousa",
        address: "Quadra 06 conjunto E casa 10, Brazlândia",
        phone: "(61) 98441-2462",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Ana Caroline Morais da Costa",
        address: "Quadra 04, conjunto L, casa 04 - Brazlândia",
        phone: "(61) 98550-6108",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Guilherme Alves da Mota Caitano",
        address: "Quadra 2A, casa 7, Incra 08 - Brazlândia",
        phone: "(61) 98646-7885",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Diego Henrique Bispo Nogueira",
        address: "Quadra 6E conjunto B Casa 16 A- Arapoanga DF",
        phone: "(61) 99634-9890",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Maria Luiza do Nascimento Silva",
        address: "Quadra 6 conjunto i casa 11 - Arapoanga- DF",
        phone: "(61) 99227-3503",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "James Ribeiro Magalhães de Souza",
        address: "Quadra 11b, conjunto J, casa 06 - Arapoangas/DF",
        phone: "(61) 98411-2134",
      },
    ],
  },
  {
    name: "Secretaria",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Fernanda dos Reis Oliveira Pinheiro",
        wifePhone: "(61) 99110-4646",
        husbandName: "Tio João Carlos da Rocha Pinheiro Júnior",
        husbandPhone: "(61) 99125-9920",
        address: "Qs 612 Conjunto B Lote 1 Apt 601 Residencial Bougainville - Samambaia Norte",
      },
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Ana Clara Reis Portela",
        wifePhone: "(61) 99315-7694",
        husbandName: "Tio Mateus Marques Soares",
        husbandPhone: "(61) 99305-2998",
        address: "SGAN 906 módulo B bloco D apto 213 - Cond. Studios - Asa Norte",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Pâmella da Natividade Diniz Rapôzo",
        address: "QD 206, Lote 04, Apto 203 (Residencial Tuim) - Águas Claras",
        phone: "(61) 98213-6373",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriella Rocha Cesar",
        address: "SHIN, casa 5, Bloco N1, Apto 107 - Lago Norte",
        phone: "(61) 99862-4522",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Bianca Sousa do Nascimento",
        address: "Quadra 10 Conj. B Casa 27 - Varjão",
        phone: "(61) 99869-4001",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Bruna Xavier Bomfim",
        address: "SHCES 913 BL B Apt 405 - Cruzeiro",
        phone: "(61) 99840-8877",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriel de Carvalho Oliveira",
        address: "Quadra 5, Conjunto K, Casa 4, Varjão-DF",
        phone: "(61) 99258-5595",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Laura Couto de Souza Nunes",
        address: "SHA, Chácara 47 A, Conjunto 3, Casa 3, Arniqueiras-DF",
        phone: "(61) 99552-9798",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Isis Pereira dos Santos Silva",
        address: "QR 02 Conjunto A Casa 46 - Candangolandia",
        phone: "(61) 98414-5203",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Lucas Feliciano Rodrigues",
        address: "Quadra 35 conjunto H Casa 15 Vila São José Brazlandia",
        phone: "(61) 99623-6899",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Soane José de Alcantara Oliveira",
        address: "Quadra 37 conjunto B casa 10 - Vila São José, Brazlândia",
        phone: "(61) 99854-4337",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Ysabella dos Santos Silva",
        address: "Quadra 02 Conjunto J Casa 46 Arapoanga DF",
        phone: "(61) 99812-5110",
      },
    ],
  },
  {
    name: "Ordem e Limpeza",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Mayara Maryana da Costa Neves",
        wifePhone: "(61) 99815-7107",
        husbandName: "Tio Rodrigo Casimiro Morais",
        husbandPhone: "(61) 99882-3328",
        address: "QD 4, Conj B Casa 23 - Setor Sul, Gama",
      },
      {
        type: "CASAL",
        subcategory: "Casal apoio",
        wifeName: "Tia Natália Alves de Souza Pereira",
        wifePhone: "(61) 98428-0955",
        husbandName: "Tio José Aildo Pereira",
        husbandPhone: "(61) 98482-1948",
        address: "Rua 12 Chácara 320 Casa 19A - Cond. Imperio do Sol - Vicente Pires",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Vitor de Oliveira Coelho",
        address: "QE 14 Conj. E Casa 24 - Guará",
        phone: "(61) 99665-8577",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "João Filipe Bonfim Barreira",
        address: "SQN 103 Bloco B - Asa Norte",
        phone: "(61) 99422-6882",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Rita Gabriele Carvalho da Silva",
        address: "SMLN MI 13 Conj. 2 Casa 9A 01 - Lago Norte",
        phone: "(61) 99185-1508",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriel Resende Assis",
        address: "SHTN 2, Bloco N Apto 401 (Cond. Life Resort) - Asa Norte",
        phone: "(31) 99866-6631",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Ícaro Rocha",
        address: null,
        phone: "(21) 99927-2150",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Lauro Henrique Moreira de Oliveira",
        address: "SQN 103 Bloco G Apto 103 - Asa Norte",
        phone: "(32) 99136-0560",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Matheus Fernog",
        address: "Quadra 02 conjunto H casa 15 Setor Veredas Brazlândia",
        phone: "(61) 99891-1530",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Thales Ramon de Oliveira",
        address: "Chácara 13b cascalheira setor de chácara brazlandia",
        phone: "(61) 99165-4455",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Nathalia Alves da Mota Caitano",
        address: "Quadra 2A, casa 7, Incra 08, Brazlândia",
        phone: "(61) 98315-3471",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Gabriel Henrique dos Santos de Souza",
        address: "Quadra 4 sul bloco c casa 07 - Brazlândia",
        phone: "(61) 99998-3748",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens membros",
        name: "Jáiza Gabrielle Xavier da Silva",
        address: "Quadra 07 Conjunto i Casa 05, Arapoanga DF",
        phone: "(61) 99103-4941",
      },
    ],
  },
  {
    name: "Círculo Amarelo",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Dayane Guerra Santos",
        wifePhone: "(61) 99234-1350",
        husbandName: "Tio Yuri Guerra de Araújo",
        husbandPhone: "(61) 99105-6878",
        address: "QMSW 06, bloco C, apto 20 - Sudoeste",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Francisco Ítalo Rios Andrade",
        address: "SQN 306, Bloco B, Apto 106 - Asa Norte",
        phone: "(61) 98252-6221",
      },
    ],
  },
  {
    name: "Círculo Azul",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Rosa Maria Lopes Pavão da Silva",
        wifePhone: "(61) 98303-3462",
        husbandName: "Tio Roberto Durão da Silva",
        husbandPhone: "(61) 98281-7973",
        address: "SQN 103 Bl G apto 303",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Maria Eduarda Fontes Wisnesky",
        address: "SQNW 103 Bloco F Apto 103 - Noroeste",
        phone: "(61) 98230-7673",
      },
    ],
  },
  {
    name: "Círculo Rosa",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Thalita Viana da Silva Matos",
        wifePhone: "(61) 99988-4744",
        husbandName: "Tio Bruno Galvão" || "Tio Bruno Matos Galvão",
        husbandPhone: "(61) 99988-4733",
        address: "AC 2 lotes 01/02 e 12 Bloco B Apto 601 - Riacho Fundo I",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Isadora da Silva Ferreira",
        address: "QN 7, Q. 14, Casa 26 - Riacho Fundo I",
        phone: "(61) 98603-3239",
      },
    ],
  },
  {
    name: "Círculo Verde",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Vitória Cristina da Silva Miranda Santos",
        wifePhone: "(61) 98117-1974",
        husbandName: "Tio Lucas Sávio dos Santos",
        husbandPhone: "(61) 99509-0442",
        address: "QS 12 Conj 5B casa 09 - Riacho Fundo I",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Maria Clara Pavão da Silva",
        address: "SQN 113, Bloco J, Apartamento 405, Asa Norte-DF",
        phone: "(61) 98304-4836",
      },
    ],
  },
  {
    name: "Círculo Vermelho",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Graziela Furtado Scarpelli",
        wifePhone: "(61) 98116-5145",
        husbandName: "Tio Enrique Maia Rocha",
        husbandPhone: "(61) 98155-7272",
        address: "SQNW 107 - Bloco E apto 502",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Wallysson Cardoso Soares",
        address: "QR 3 Conjunto D Casa 58 - Candangolândia",
        phone: "(61) 99181-5980",
      },
    ],
  },
  {
    name: "Externa",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Ana Paula dos Santos Soares Nunes",
        wifePhone: "(61) 98206-4102",
        husbandName: "Tio Pedro Paulo Gomes Nunes",
        husbandPhone: "(61) 98167-7762",
        address: "SHA Conj 3 Lote 3 casa 3 chácara 47 - Arniqueiras",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Joselina Gomes Nunes Gesteira",
        wifePhone: "(61) 99954-4341",
        husbandName: "Tio Edson Lopes Gesteira",
        husbandPhone: "(61) 98402-0586",
        address: "QR 1 A Conjunto T casa 20, Candangolândia",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Shayenni Abdala",
        wifePhone: "(61) 99145-2147",
        husbandName: "Tio Gabriel Abdala",
        husbandPhone: "(61) 99169-7008",
        address: "SQNW 108 Bl D Apto 502 - Noroeste",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Lúcia de Fátima Saraiva Silva",
        wifePhone: "(61) 98275-8768",
        husbandName: "Tio Eldson Pereira dos Santos",
        husbandPhone: "(61) 98296-5203",
        address: "QR- 1A Conj RS Casa 01 - Candangolândia",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Lívia Bastos de Sousa da Costa",
        wifePhone: "(61) 985022434",
        husbandName: "Tio Hermani Duarte da Costa",
        husbandPhone: "(61) 99332-1389",
        address: "SQN 102 Bloco A Apartamento 307 - Asa Norte",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Daniella Nunziato Teixeira Emídio de Andrade",
        wifePhone: "(61) 98236-5079",
        husbandName: "Tio César Teixeira Emídio de Andrade",
        husbandPhone: "(61) 98304-9631",
        address: "SQN 313 Bloco E Apartamento 107 - Asa Norte",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Betânia Maria Soares da Silva Santos",
        wifePhone: "(61) 98460-3604",
        husbandName: "Tio Ricardo de Souza Santos",
        husbandPhone: "(61) 99915-3366",
        address: "Cond. RK, conjunto Antares, QD D casa 04 - Sobradinho",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Manuela Gomes Campos Borel",
        wifePhone: "(32) 98898-1901",
        husbandName: "Tio Aloisio Tiago Borel",
        husbandPhone: "(32) 99163-4964",
        address: "SQN 306 Bloco H, Apartamento 107 - Asa Norte",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Rayane Kelly Gomes Bastos",
        wifePhone: "(61) 99694-6007",
        husbandName: "Tio Edvan Araújo dos Santos",
        husbandPhone: "(61) 99115-6623",
        address: "Sha Conjunto 3 Chácara 47A lote 05 - Arniqueira",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Amanda Lesjak Santos Teixeira",
        wifePhone: "(61) 99692-0127",
        husbandName: "Tio Vitor Sacramento",
        husbandPhone: "(61) 99526-9509",
        address: "SMPW Qd 29 Conjunto 1 Lote 3 Casa D - Park Way",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Karla Couto Nunes",
        wifePhone: "(61) 99408-7380",
        husbandName: "Tio Rafael Ramos",
        husbandPhone: "(61) 99175-9937",
        address: "AE 1/4 Setor Central, Condomínio Flex Gama Bloco B Apto 2007",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Laura Barreto Neves Rocha",
        wifePhone: "(61) 98324-0200",
        husbandName: "Tio Marcus Vinicius de Carvalho",
        husbandPhone: "(61) 99830-0250",
        address: "Cond. Jardim América, módulo F casa 14, SH Contagem - Sobradinho",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Cristiane Assunção Matos Lameira",
        wifePhone: "(61) 99973-1221",
        husbandName: "Tio João César Ramos Ehrich",
        husbandPhone: "(61) 98383-0540",
        address: "SQSW 504 Bloco K Apartamento 508",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Daiane Rodrigues Aureliano Rebouças",
        wifePhone: "(61) 98448-9467",
        husbandName: "Tio Edivan Nogueira Rebouças Junior",
        husbandPhone: "(61) 98613-0301",
        address: "Av Pau Brasil, Lt 18, Cond Res Pau Brasil, Apto 1501 B",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Ermione Mendes Oliveira Pedroso",
        wifePhone: "(61) 99333-8412",
        husbandName: "Tio Guilherme Gesteira Pedroso",
        husbandPhone: "(61) 99948-8412",
        address: "Qc 15, Bloco N2, Apartamento 12 - Jardim Botânico",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Lorainy Stolle da Cunha Aguiar",
        wifePhone: "(61) 99170-7884",
        husbandName: "Tio Jordan Fernandes Aguiar da Silva",
        husbandPhone: "(61) 99303-9844",
        address: "QE 42 Conjunto E1 Casa 10 - Guará 2",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Nathália de Araújo de souza",
        wifePhone: "(61) 98263-2662",
        husbandName: "Tio José Ranclenisson Lopes Moreira",
        husbandPhone: "(61) 98248-9777",
        address: "AC 1 Lote 1 Bloco A, Apartamento 407 - Riacho Fundo 1",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Eduarda Almeida",
        wifePhone: "(61) 99105-5428",
        husbandName: "Tio Lucas Almeida",
        husbandPhone: "(61) 99860-4620",
        address: "Qr O Conjunto VC Lote 36, Apartamento 02 - Candangolândia",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Isabela Costa Pereira",
        wifePhone: "(61) 98102-6502",
        husbandName: "Tio Pedro Henrique de Jesus Spinosa",
        husbandPhone: "(61) 99180-7140",
        address: "2ª Avenida Bloco 585 B, Apartamento 202 - N. Bandeirante",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Lílian Carvalho Neves Lubiana",
        wifePhone: "(61) 99546-4949",
        husbandName: "Tio Luciano Lubiana",
        husbandPhone: "(61) 99543-5005",
        address: "SQN 103 Bloco J, Apartamento 401 - Asa Norte",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Beatriz do Nascimento Barbosa",
        wifePhone: "(61) 99852-3030",
        husbandName: "Tio Daniel Rodrigo de Souza Silva",
        husbandPhone: "(61) 99346-9630",
        address: "QR1A Conjunto RE Casa 46 - Candangolândia",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Catia Fontoura de Fontes Wisnesky",
        wifePhone: "(61) 98230-7687",
        husbandName: "Tio Marcelo Wisnesky Soares",
        husbandPhone: "(61) 98232-3215",
        address: "SQNW 103 Bloco F Apto 103 - Noroeste",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Mayra Cristina Lopes Gonçalves Silva",
        wifePhone: "(61) 99656-6795",
        husbandName: "Tio Thiago Augusto dos Santos Silva",
        husbandPhone: "(61) 99664-7563",
        address: "Cond. Vivendas Alvorad 2 Conj. N Lote 3A - Sobradinho",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Marilene Vital Silva",
        wifePhone: "(61) 99943-9052",
        husbandName: "Tio Mauro Sérgio da Silva",
        husbandPhone: "(61) 98137-5566",
        address: "Quadra 4 Conjunto E casa 17 - Candangolândia",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Tânia de Paiva Medeiros",
        wifePhone: "(61) 99321-6799",
        husbandName: "Tio Marcos Antônio da Silva",
        husbandPhone: "(61) 99239-0739",
        address: "SCRN 707/705 Bloco D Entrada 15 Apto 402 - Asa Norte",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Edna Lopes Gesteira Mariano",
        wifePhone: "(61) 99956-2463",
        husbandName: "Tio Valdemir Wagner Mariano",
        husbandPhone: "(61) 99909-6604",
        address: "QS 16, Conjunto 2, Casa 8, Riacho Fundo I - DF",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Marlene Teixeira de Sousa Coutinho",
        wifePhone: "(61) 99177-6369",
        husbandName: "Tio Juscelino de Sousa Silva Coutinho",
        husbandPhone: "(61) 98252-6156",
        address: "QR5 conjunto A casa 32 - Candangolândia",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Kalene",
        husbandName: "Tio Jomar",
        address: "casal dirigente - implantação Nossa Senhora do Carmo",
      },
      {
        type: "CASAL",
        subcategory: "Casais membros",
        wifeName: "Tia Mônica",
        husbandName: "Tio Tarcisio",
        address: "casal dirigente - implantação Nossa Senhora do Carmo",
      },
    ],
  },
  {
    name: "Equipe Dirigente — Montagem",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Jéssica Alves Pereira da Rocha",
        wifePhone: "(61) 98531-1948",
        husbandName: "Tio Jefferson Andrade da Rocha",
        husbandPhone: "(61) 99209-3589",
        address: "Rua 3a - Ed. Água Marinha - Vicente Pires",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Amanda Victoria Prado Lages",
        address: "SGAN 915 Módulo F Cond. Parque Norte Brasília Bloco C Apto 9",
        phone: "(61) 99837-7337",
      },
    ],
  },
  {
    name: "Equipe Dirigente — Finanças",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Larissa Guimarães Portela",
        wifePhone: "(61) 98133-6984",
        husbandName: "Tio Daniel Cabral Portela",
        husbandPhone: "(61) 99292-1401",
        address: "SQN 203 Bloco E Apto 505 - Asa Norte",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Fabiano Sampaio Rocha",
        address: "Quadra 3, Conjunto 2, Casa 21, Taquari-DF",
        phone: "(61) 98299-1320",
      },
    ],
  },
  {
    name: "Equipe Dirigente — Palestra",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Cristina Fujita Barroso Muniz",
        wifePhone: "(61) 98213-3903",
        husbandName: "Tio André Sousa Barroso Fujita Barroso",
        husbandPhone: "(61) 98342-8300",
        address: "SCRN 702/703 Bloco F apto 101 - Asa Norte",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Gabriela C. de Andrade C. Reis",
        address: "SQN 306 Bloco D Apartamento 405 - Asa Norte",
        phone: "(61) 99906-8118",
      },
    ],
  },
  {
    name: "Equipe Dirigente — Fichas",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Michele Cabreira de Andrade Reis",
        wifePhone: "(61) 99906-8113",
        husbandName: "Tio Marcelo Corrêa Reis",
        husbandPhone: "(61) 99906-8112",
        address: "SQN 306 Bloco D Apartamento 405 - Asa Norte",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Aline Sousa",
        address: "Rua 1, Lote 14, Apartamento 8, Asa Sul-DF",
        phone: "(61) 98252-6048",
      },
    ],
  },
  {
    name: "Equipe Dirigente — Pós-Encontro",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Juliana Tessari Dias Rohr",
        wifePhone: "(61) 99139-0860",
        husbandName: "Tio José Ivanildo Dias Júnior",
        husbandPhone: "(61) 99129-5552",
        address: "SQNW 107, Bloco I, Apartamento 202, Noroeste-DF",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens coordenadores",
        name: "Júlia de Oliveira Baur",
        address: "SQN 102 Bloco D Apartamento 101 - Asa Norte",
        phone: "(21) 98932-4675",
      },
    ],
  },
  {
    name: "Articulação Arquidiocesana",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Angélica Cristina de Melo Silva",
        wifePhone: "(61) 99855-8332",
        husbandName: "Tio João Henrique de Souza Silva",
        husbandPhone: "(61) 99840-0173",
        address: "QD 3 Norte, bloco C, loja 9, Ap 101 - Brazlândia",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Filipi Fabiano de Paulo Oliveira",
        address: "Qd 35 cj H casa 17 Brazlândia",
        phone: "(610) 98444-5860",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Letícia Tainara Melo Vasconcelos",
        address: "QD 45 Conj I casa 23 - Brazlândia",
        phone: "(61) 98325-4158",
      },
    ],
  },
  {
    name: "Vicariato Norte",
    members: [
      {
        type: "CASAL",
        subcategory: "Casal coordenador",
        wifeName: "Tia Eliane Lima Carvalho de Andrade",
        wifePhone: "(61) 99130-3656",
        husbandName: "Tio Antônio Marcos de Andrade",
        husbandPhone: "(61) 99219-5985",
        address: "QD 16 Conj. F casa 10 - Arapoanga",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Élvis David Carvalho de Paula",
        address: "QD 12 Conj. D casa 9 C - Araponga",
        phone: "(61) 98377-6780",
      },
      {
        type: "JOVEM",
        subcategory: "Jovens apoio",
        name: "Samara Martins de Oliveira",
        address: "QD 6 Conj. I casa 29A - Araponga",
        phone: "(61) 99827-4532",
      },
    ],
  },
  {
    name: "Diretor Espiritual",
    members: [
      {
        type: "JOVEM",
        subcategory: "Diretor Espiritual",
        name: "Padre Rafael Souza Santos",
        address: "Santuário Nossa Senhora da Saúde",
        phone: "(61) 3326-1180",
      },
    ],
  },
];

async function main() {
  console.log("Seeding teams and members for IV EJC Nossa Senhora da Saúde...");

  for (const teamItem of teamsData) {
    const team = await prisma.team.upsert({
      where: {
        name_system: {
          name: teamItem.name,
          system: "SEGUEME",
        },
      },
      update: {},
      create: {
        name: teamItem.name,
        system: "SEGUEME",
      },
    });

    console.log(`Team: ${team.name} (ID: ${team.id})`);

    // Clean existing members for this team to avoid seeding duplicate entries on re-run
    await prisma.member.deleteMany({
      where: {
        teamId: team.id,
      },
    });

    for (const memberItem of teamItem.members) {
      await prisma.member.create({
        data: {
          type: memberItem.type,
          subcategory: memberItem.subcategory,
          teamId: team.id,
          name: memberItem.name || null,
          phone: memberItem.phone || null,
          address: memberItem.address || null,
          wifeName: memberItem.wifeName || null,
          wifePhone: memberItem.wifePhone || null,
          husbandName: memberItem.husbandName || null,
          husbandPhone: memberItem.husbandPhone || null,
        },
      });
    }
    console.log(`Added ${teamItem.members.length} members.`);
  }

  console.log("Seeding finished successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
